# -*- coding: utf-8 -*-
"""Demo_KFold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gecxD3B7wtphJAUf-BxWrFj-rEt3CQeH

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

### Not for Grading

## Learning Objectives

At the end of the experiment, you will be able to:


* split dataset into k consecutive folds

## AI /ML Technique

### K-Fold Cross Validation

In k-fold cross-validation, the original sample is randomly partitioned into k equal sized subsamples. Of the k subsamples, a single subsample is retained as the validation data for testing the model, and the remaining k − 1 subsamples are used as training data. The cross-validation process is then repeated k times, with each of the k subsamples used exactly once as the validation data. The k results can then be average to produce a single estimation.

## Setup Steps
"""

#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2508796" #@param {type:"string"}

#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "2345345345" #@param {type:"string"}

#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "Demo_KFold" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Purchase_Dataset.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/submissions/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword(), "batch" : ""}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook, "batch" : ""}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")

"""## **Section I: Understand the k-fold data split**

#### Importing required packages
"""

# Import required packages
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier

x = np.array(["yellow", "blue", "pink", "white", "red", "violet", "orange", "green"])

# Set the KFold module for 4 splits:
kf = KFold( n_splits=4 )
i = 0

# Divide the data into trainindex and testindex
# K splits are iterated
for trainindex, testindex in kf.split(x):
    print( "Round :", i, ":" )
    i += 1

    print( "Training index", trainindex, "Training set is:", x[trainindex])
    print( "Testing index", testindex, "Testing set is:", x[testindex])

"""### **Section II: K-fold using Purchase_Dataset**"""

# Read the data in to a pandas dataframe
data = pd.read_csv("/content/Purchase_Dataset.csv")

print( "Shape of data", data.shape)
# The first few lines of data to verify the data
data.head()

# Get unique values of Gender
#data["Gender"].unique()

# Convert categorial values to numerical values
#data["Gender"] = data["Gender"].replace([ "Male", "Female"],[ 0, 1])
#data["Gender"].head()

"""LabelEncoder() is a utility class to help normalize labels such that they contain only values between 0 and n_classes-1. It can also be used to transform non-numerical labels to numerical labels"""

# Convert categorial values to numerical values using label encoder
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data["Gender"] = le.fit_transform(data["Gender"])  # fit_transform, Fit label encoder and return encoded labels.

# X will be our independent/feature variables and y is our dependent/target variable
X = data[["Age", "EstimatedSalary", "Gender"]]
y = data["Purchased"]

"""#### Splitting the data using Kfold"""

# Set the our KFold module for 4 splits:
kf = KFold(n_splits=4)

x_data = X.values
i = 1
# Divide the data into trainindex and testindex
# K splits are iterated
for train_index, test_index in kf.split(x_data):

    x_train, x_test, y_train, y_test = x_data[train_index], x_data[test_index], y[train_index], y[test_index]
    print( "Split :", i, ":" )
    i += 1
    print( "Distribution of Training labels:", y_train.values)
    print( "Distribution of Testing labels:", y_test.values)
    print("--------------------------------------")

"""## Please answer the questions below to complete the experiment:"""

#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

#@title If it was very easy, what more you would have liked to have been added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "sdgfdjhfgjfhjh" #@param {type:"string"}

#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]

#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Somewhat Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

#@title Run this cell to submit your notebook  { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id =return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")