# -*- coding: utf-8 -*-
"""RepresentationDataAIML27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SczBIIJ1YZORUdVJHGcBWjjBuu4kBdq2
"""

from math import sqrt

h = sqrt(0.35 ** 2+0.35 **2)
h

sat = sqrt(0.7 **2 + 0.6 **2)
sat

0.455/(0.494*0.922)

!wget https://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

import numpy as np
emb = {}
with open("/content/glove.6B.50d.txt",encoding="utf8") as f:
  for line in f:
    parts = line.split()
    emb[parts[0]] = np.array(parts[1:],dtype=np.float32)
print(emb["king"][:5])
print(len(emb["king"]))

def cosine(a,b):
  return a @ b /(np.linalg.norm(a)*np.linalg.norm(b))

result = emb["king"] -emb["man"] +emb["woman"]
inputs = {"king","man","woman"}
best = max((w for w in emb if w not in inputs),key=lambda w:cosine(result,emb[w]))
print(best)

!pip install gensim

import gensim.downloader as api

model = api.load("glove-wiki-gigaword-100")

print(model.most_similar(positive=["king","woman"],negative=["man"],topn=1))

sentences =["the cat sat on mat",
            "the dog sat on mat",
            "the cat ate fish"]

tokenized = [s.split() for s in sentences]

print(tokenized)

from gensim.models import Word2Vec
sentences =[
            ['the', 'cat', 'sat', 'on', 'mat'],
            ['the', 'dog', 'sat', 'on', 'mat'],
            ['the', 'cat', 'ate', 'fish']
            ]
model = Word2Vec(sentences,vector_size=5,window=2,min_count=1,sg=1,epochs=500)

print(model.wv["cat"])

print(model.wv.most_similar("cat",topn=1))

predictions = model.predict_output_word(context_words_list=["cat","on"],topn=1)
print(predictions)

pip install -U spacy

!python -m space download en_core_web_sm

import spacy

# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_sm")

text = " john is working on Google in New Gersy"

doc = nlp(text)

for ent in doc.ents:
  print(ent.text,ent.label_)

#Rawtext->tokenize->postag->chunk->parse->NER->MEaning

print("Raw text",text)

for token in doc:
  print(token.text)

for token in doc:
  print(token.text,"->",token.pos_,"(",token.tag_,")")

for chunk in  doc.noun_chunks:
  print(chunk.text,"->",chunk.label_)

for token in doc:
  print(token.text,"->",token.dep_)

for ent in doc.ents:
  print(ent.text,"->",ent.label_)

for token in doc:
    if token.dep_ =="nsubj":
        print("Subject:",token.text)
    if token.dep_ =="Root":
        print("Acttion:",token.text)

