# -*- coding: utf-8 -*-
"""U3_MH1_CNN_with_Pytorch (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_NoaLdmS5q6rNAqdpTd3ycEZw7QWqg9

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Problem Statement

To identify and classify images as cats or dogs

## Learning Objectives

At the end of the experiment, you will be able to :

* Load and prepare images for the model using Pytorch
* Develop a CNN model and improve model performance
"""

#@title Mini-hackathon walkthrough
from IPython.display import HTML

HTML("""<video width="854" height="480" controls>
  <source src="https://cdn.talentsprint.com/aiml/aiml_2020_b14_hyd/experiment_details_backup/Pytorch_CNN_cats_and_dogs.mp4" type="video/mp4">
</video>
""")

"""## Dataset

The Dogs and Cats dataset is a standard computer vision dataset that involves classifying photos as either containing a dog or cat. The train folder contains ~22k images of dogs and cats. Each image in this folder has the label as part of the filename. The test folder contains ~2k images, named according to a numeric id.

## Grading = 10 Marks

## Setup Steps
"""

#@title Run this cell to download the dataset

from IPython import get_ipython
ipython = get_ipython()

notebook="U3_MH1_CNN_with_Pytorch" #name of the notebook
Answer = "This notebook is graded by mentors on the day of hackathon"
def setup():
#
   ipython.magic("sx wget http://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Cat_Dog_data_B17.zip")
   ipython.magic("sx unzip -qq Cat_Dog_data_B17.zip")
   print ("Setup completed successfully")
   return

setup()

"""## Basic Pytorch packages

**torchvision:**  This package is used to load and prepare the dataset. Using this package we can perform/apply transformations on the input data.

**transforms:**  This package is  used to perform preprocessing on images and operations sequentially.

**nn:**  This package provides an easy and modular way to build and train simple or complex neural networks.

**optim:** This package is used for  implementing various optimization algorithms
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
import matplotlib.pyplot as plt
# %pip install torch torchvision

from torchvision import datasets, transforms
from torch import nn
import torch.nn.functional as F
from torch import optim
from torch.autograd import Variable

"""## **Stage 1:** Define Transformations and import data

### 1 Marks - > Compose multiple transformations with the following conditions

1. Transform image size to 128 by using Resize()

2. Convert image to Grayscale

3. Transform the image into a number using tensor

4. Normalize the tensor image with 0.5

[Hint](https://pytorch.org/vision/stable/transforms.html)
"""

image_size = (128,128)

transformations = transforms.Compose([
    transforms.Resize(image_size),
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

"""### 1 Mark -> Load the dataset with the defined transformations

PyTorch includes a package called torchvision which is used to load and prepare the dataset. It includes two basic functions namely Dataset and DataLoader which helps in the transformation and loading of the dataset.

1. Dataset is used to read and transform a data point from the given dataset.  Note that, the data is not loaded on memory by now.

2. DataLoader is used to shuffle and batch the data. It can be used to load the data in parallel with multiprocessing workers. The Data loader reads the data and puts it into memory.



[Hint](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html)
"""

import torch

batch_size = 100

# ★ IMPROVEMENT: Data augmentation for training (reduces overfitting)
# Original code only used 'transformations' (Resize + Grayscale + ToTensor + Normalize)
# Added RandomHorizontalFlip and RandomRotation to artificially increase dataset variety
# This forces the model to learn features that are invariant to flips and slight rotations
train_transforms = transforms.Compose([
    transforms.Resize(image_size),
    transforms.Grayscale(num_output_channels=1),
    transforms.RandomHorizontalFlip(),       # ★ NEW: Randomly flip images horizontally (50% chance)
    transforms.RandomRotation(10),           # ★ NEW: Randomly rotate by up to 10 degrees
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_set = datasets.ImageFolder(f'/content/Cat_Dog_data/train', transform = train_transforms)

train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)



"""### 1 Marks -> Plot the 5 images of Cats and 5 images of Dogs"""

# Plot 5 cats and 5 dogs
fig, axes = plt.subplots(2, 5, figsize=(15, 6))

cat_count = 0
dog_count = 0

for img, label in train_set:
    if label == 0 and cat_count < 5:  # cats
        axes[0, cat_count].imshow(img.squeeze(), cmap='gray')
        axes[0, cat_count].set_title('Cat')
        axes[0, cat_count].axis('off')
        cat_count += 1
    elif label == 1 and dog_count < 5:  # dogs
        axes[1, dog_count].imshow(img.squeeze(), cmap='gray')
        axes[1, dog_count].set_title('Dog')
        axes[1, dog_count].axis('off')
        dog_count += 1
    if cat_count == 5 and dog_count == 5:
        break

plt.tight_layout()
plt.show()

"""## **Stage2:** CNN Model

Neural Networks are inherited from the nn.Module class.

Define a neural network by using two functions \__init__ and forward function.

1. In the \__init__  function, perform a series of convolutions and pooling operations to detect the features. Apply a fully connected layer on top of these features. Apply LogSoftmax at the output layer to improve the performance.

2. The forward function is called on the Neural Network which takes the inputs and passes through the different layers that have been defined in the \__init__.  The output of both convolution and pooling layers is 3D whereas a fully connected layer expects a 1D vector of numbers. So flatten the output of the final pooling layer to a vector and that becomes the input to the fully connected layer.

[Hint](https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_convolutional_neuralnetwork/)

### 3 Marks -> Create CNN Model
"""

class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()

        # Sample Convolution Layer 1
        self.cnn1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=5, stride=1, padding=2) # output size of the first convolutional layer is 16*128*128
        self.bn1 = nn.BatchNorm2d(16)
        self.relu1 = nn.ReLU()
        # Sample Maxpool for the Convolutional Layer 1
        self.maxpool1 = nn.MaxPool2d(kernel_size=4, stride=4) # Maxpooling reduces the size by kernel size. After Maxpooling the output size is 16*32*32


        # Convolution Layer 2
        self.cnn2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=5, stride=1, padding=2)
        self.bn2 = nn.BatchNorm2d(32)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool2d(kernel_size=4, stride=4)  # output: 32*8*8

        # Convolution Layer 3
        self.cnn3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=5, stride=1, padding=2)
        self.bn3 = nn.BatchNorm2d(64)
        self.relu3 = nn.ReLU()
        self.maxpool3 = nn.MaxPool2d(kernel_size=2, stride=2)  # output: 64*4*4

        # ★ IMPROVEMENT: Dropout to prevent overfitting
        # Original code had NO dropout — model memorized training data (97% train vs 88% test)
        # Dropout randomly "turns off" neurons during training, forcing others to compensate
        # This prevents co-adaptation and improves generalization to unseen images
        self.dropout_conv = nn.Dropout2d(0.25)  # ★ NEW: drops 25% of feature maps after conv layers
        self.dropout_fc = nn.Dropout(0.5)       # ★ NEW: drops 50% of neurons in FC layer

        # Fully Connected Layer
        self.fc1 = nn.Linear(64 * 4 * 4, 128)
        self.fc2 = nn.Linear(128, 2)
        self.logsoftmax = nn.LogSoftmax(dim=1)




    def forward(self, x):
        # Convolution Layer 1 and Maxpool
        out = self.cnn1(x)
        out = self.bn1(out)
        out = self.relu1(out)
        out = self.maxpool1(out)

        # Convolution Layer 2 and Maxpool
        out = self.cnn2(out)
        out = self.bn2(out)
        out = self.relu2(out)
        out = self.maxpool2(out)
        out = self.dropout_conv(out)  # ★ NEW: Dropout after conv layer 2

        # Convolution Layer 3 and Maxpool
        out = self.cnn3(out)
        out = self.bn3(out)
        out = self.relu3(out)
        out = self.maxpool3(out)
        out = self.dropout_conv(out)  # ★ NEW: Dropout after conv layer 3

        # Flatten the output
        out = out.view(out.size(0), -1)

        # Fully Connected Layer and LogSoftmax
        out = self.fc1(out)
        out = F.relu(out)
        out = self.dropout_fc(out)  # ★ NEW: Dropout before final classification layer
        out = self.fc2(out)
        out = self.logsoftmax(out)
        return out

"""### 1 Mark -> Create an instance of the model and Declare the loss function and optimizer

"""

# To run the training on GPU
print(torch.cuda.is_available())

device  =  torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CNNModel()
model = model.to(device)
print(model)

criterion = nn.NLLLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

"""## **Stage 3:** Train the Model and validate it continuously to calculate the loss and accuracy for the train dataset across each epoch.

### Expected training accuracy is above 90%

### 2 Marks -> Iterate over images in the train_loader and perform the following steps.

1. First, we zero out the gradients using zero_grad()

2. We pass the data to the model. Convert the data to GPU before passing data  to the model

3. We calculate the loss using a Loss function

4. Perform Backward pass using backward() to update the weights

5. Optimize and predict by using the torch.max()

6. Calculate the accuracy of the train dataset

[Hint](https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_convolutional_neuralnetwork/)
"""

# Training loop
# ★ IMPROVEMENT: Increased epochs from 10 to 15
# Original: 10 epochs. With dropout, the model trains slower (some neurons disabled)
# so it needs more epochs to converge. 15 epochs gives dropout enough time to regularize.
num_epochs = 35
train_losses = []
train_accuracies = []

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        # Zero out gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(images)

        # Calculate loss
        loss = criterion(outputs, labels)

        # Backward pass
        loss.backward()

        # Optimize
        optimizer.step()

        # Track loss and accuracy
        running_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct / total
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.2f}%')
    if epoch_accuracy >= 90:
      break
print(f'\nFinal Training Accuracy: {train_accuracies[-1]:.2f}%')

"""## **Stage 4:** Testing Evaluation for CNN model

### Expected performance of test evaluation is above 90%

### 1 Marks -> Evaluate model with the given test data

1. Transform and load the test images.

2. Pass the test data through the model (network) to get the outputs

3. Get the predictions from a maximum value using torch.max

4. Compare with the actual labels and get the count of the correct labels

5. Calculate the accuracy based on the count of correct labels
"""

val_set = datasets.ImageFolder(f'/content/Cat_Dog_data/test', transform = transformations)

val_loader = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)

"""Dataset Counts"""

import collections

# Count images in train_set
train_counts = collections.Counter(train_set.targets)
print("Train Set Image Counts:")
print(f"  Cats: {train_counts[0]}")
print(f"  Dogs: {train_counts[1]}")

# Count images in val_set (test set)
val_counts = collections.Counter(val_set.targets)
print("\nTest Set Image Counts:")
print(f"  Cats: {val_counts[0]}")
print(f"  Dogs: {val_counts[1]}")

(11300+11250)/100

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

"""## Visualizing Feature Maps at Each Convolution Layer

This shows **what the CNN sees** at each stage:
- **Layer 1**: Edges, textures, simple gradients
- **Layer 2**: Parts — combinations of edges (ears, eyes, noses)
- **Layer 3**: High-level structures — face shapes, body outlines

Each small image below is one "filter's" output — the brighter the pixel, the more that filter is activated by that region.
"""

# Visualize what each convolution layer extracts
import numpy as np

# Get a sample image
sample_img, sample_label = train_set[0]
class_names = train_set.classes
print(f"Sample image class: {class_names[sample_label]}")

# Put model in eval mode and pass image through each layer
model.eval()
x = sample_img.unsqueeze(0).to(device)  # Add batch dimension

# Extract feature maps at each conv layer
with torch.no_grad():
    # After Conv1 + ReLU (before pooling)
    conv1_out = model.relu1(model.bn1(model.cnn1(x)))
    pool1_out = model.maxpool1(conv1_out)

    # After Conv2 + ReLU (before pooling)
    conv2_out = model.relu2(model.bn2(model.cnn2(pool1_out)))
    pool2_out = model.maxpool2(conv2_out)

    # After Conv3 + ReLU (before pooling)
    conv3_out = model.relu3(model.bn3(model.cnn3(pool2_out)))

# Move to CPU for plotting
conv1_maps = conv1_out.cpu().squeeze(0)  # Shape: (16, 128, 128)
conv2_maps = conv2_out.cpu().squeeze(0)  # Shape: (32, 8, 8)
conv3_maps = conv3_out.cpu().squeeze(0)  # Shape: (64, 4, 4)

# --- Plot Original Image ---
fig, axes = plt.subplots(1, 1, figsize=(3, 3))
axes.imshow(sample_img.squeeze(), cmap='gray')
axes.set_title(f'Original Image ({class_names[sample_label]})')
axes.axis('off')
plt.show()

# --- Plot Conv Layer 1 Feature Maps (show first 16 filters) ---
fig, axes = plt.subplots(2, 8, figsize=(16, 4))
fig.suptitle('Conv Layer 1 — Edge/Texture Detection (16 filters, 128×128)', fontsize=12)
for i in range(16):
    row, col = i // 8, i % 8
    axes[row, col].imshow(conv1_maps[i], cmap='viridis')
    axes[row, col].set_title(f'F{i+1}', fontsize=8)
    axes[row, col].axis('off')
plt.tight_layout()
plt.show()

# --- Plot Conv Layer 2 Feature Maps (show first 16 of 32 filters) ---
fig, axes = plt.subplots(2, 8, figsize=(16, 4))
fig.suptitle('Conv Layer 2 — Part Detection (16 of 32 filters, 8×8)', fontsize=12)
for i in range(16):
    row, col = i // 8, i % 8
    axes[row, col].imshow(conv2_maps[i], cmap='viridis')
    axes[row, col].set_title(f'F{i+1}', fontsize=8)
    axes[row, col].axis('off')
plt.tight_layout()
plt.show()

# --- Plot Conv Layer 3 Feature Maps (show first 16 of 64 filters) ---
fig, axes = plt.subplots(2, 8, figsize=(16, 4))
fig.suptitle('Conv Layer 3 — High-Level Structure Detection (16 of 64 filters, 4×4)', fontsize=12)
for i in range(16):
    row, col = i // 8, i % 8
    axes[row, col].imshow(conv3_maps[i], cmap='viridis')
    axes[row, col].set_title(f'F{i+1}', fontsize=8)
    axes[row, col].axis('off')
plt.tight_layout()
plt.show()

print("\n--- Summary ---")
print(f"Conv Layer 1: {conv1_maps.shape[0]} feature maps of size {conv1_maps.shape[1]}×{conv1_maps.shape[2]}")
print(f"Conv Layer 2: {conv2_maps.shape[0]} feature maps of size {conv2_maps.shape[1]}×{conv2_maps.shape[2]}")
print(f"Conv Layer 3: {conv3_maps.shape[0]} feature maps of size {conv3_maps.shape[1]}×{conv3_maps.shape[2]}")

"""## Understanding Our CNN Architecture — A Deep Dive

### The Big Picture

Our model is a **3-layer Convolutional Neural Network** that takes a grayscale 128×128 image and outputs a probability: is this a cat or a dog?

Think of it as a funnel — wide at the top (raw pixels), narrow at the bottom (binary decision).

---

### Layer-by-Layer Breakdown

#### Input
- Shape: `(batch_size, 1, 128, 128)` — 1 channel (grayscale), 128×128 pixels
- After normalization, pixel values range from -1 to +1

#### Conv Layer 1 — "Edge Detector"
```
Conv2d(1→16, kernel=5×5, padding=2) → BatchNorm → ReLU → MaxPool(4×4)
```
- **What it learns**: Basic edges, gradients, simple textures (fur patterns, ear outlines)
- **Output shape**: `(batch, 16, 32, 32)` — 16 feature maps, each 32×32
- **Why padding=2?** With kernel_size=5, padding=2 preserves spatial dimensions before pooling
- **Why MaxPool 4×4?** Aggressive downsampling (128→32) to reduce computation early

#### Conv Layer 2 — "Part Detector"
```
Conv2d(16→32, kernel=5×5, padding=2) → BatchNorm → ReLU → MaxPool(4×4)
```
- **What it learns**: Combinations of edges → ears, eyes, snouts, paws
- **Output shape**: `(batch, 32, 8, 8)` — 32 richer feature maps, each 8×8
- **Intuition**: Each of the 32 filters combines the 16 features from Layer 1 in a different way

#### Conv Layer 3 — "Object Detector"
```
Conv2d(32→64, kernel=5×5, padding=2) → BatchNorm → ReLU → MaxPool(2×2)
```
- **What it learns**: High-level structures — face shapes, body proportions, whiskers vs floppy ears
- **Output shape**: `(batch, 64, 4, 4)` — 64 abstract feature maps, each 4×4
- **Why MaxPool 2×2 here?** Gentler pooling because spatial info is already compressed

#### Flatten
```
view(batch_size, -1) → shape: (batch, 1024)
```
- Converts the 3D feature volume (64×4×4 = 1024 values) into a 1D vector
- This is the bridge between "spatial thinking" (convolutions) and "decision making" (fully connected)

#### Fully Connected Layers — "The Decision Maker"
```
Linear(1024→128) → ReLU → Linear(128→2) → LogSoftmax
```
- **FC1**: Compresses 1024 features into 128 — forces the network to find the most discriminative features
- **FC2**: Maps 128 features to 2 outputs (cat score, dog score)
- **LogSoftmax**: Converts scores to log-probabilities (works with NLLLoss)

---

### Key Design Choices Explained

| Choice | Why |
| --- | --- |
| **BatchNorm after Conv** | Stabilizes training, allows higher learning rate, acts as mild regularization |
| **ReLU activation** | Introduces non-linearity; dead-simple and proven effective |
| **Increasing channels (16→32→64)** | Deeper layers need more filters to capture complex combinations |
| **Decreasing spatial size (128→32→8→4)** | Reduces parameters; forces abstraction |
| **NLLLoss + LogSoftmax** | Mathematically equivalent to CrossEntropyLoss but split into two operations |
| **Adam optimizer (lr=0.001)** | Adaptive learning rate; converges faster than plain SGD |

---

### Parameter Count

| Layer | Parameters |
| --- | --- |
| Conv1 (1×16×5×5 + 16 bias) | 416 |
| Conv2 (16×32×5×5 + 32 bias) | 12,832 |
| Conv3 (32×64×5×5 + 64 bias) | 51,264 |
| FC1 (1024×128 + 128 bias) | 131,200 |
| FC2 (128×2 + 2 bias) | 258 |
| **Total** | **\~196K trainable params** |

This is a relatively small model — modern architectures like ResNet-18 have \~11M parameters.

## Enhancements You Can Implement — Pick Your Level

---

### Level 1: Quick Wins (10-15 min each)

#### 1. Training Curves Plot
Plot loss and accuracy vs epochs to visualize learning progress. Look for: Is loss still decreasing? Is accuracy plateauing?

#### 2. Confusion Matrix
Use `sklearn.metrics.confusion_matrix` + `seaborn.heatmap` to see which class the model struggles with more.

#### 3. Show Misclassified Images
Find images where `predicted != actual` and display them. This reveals what confuses the model (e.g., long-haired cats that look like small dogs).

#### 4. Test on Your Own Images
Download a cat/dog image from the internet, apply the same transforms, and run inference. Proves the model generalizes beyond the training set.

---

### Level 2: Architecture Improvements (20-30 min each)

#### 5. Add Dropout
Insert `nn.Dropout(0.25)` after MaxPool layers and `nn.Dropout(0.5)` before the final FC layer. This prevents overfitting by randomly zeroing neurons during training.

#### 6. Add a 4th Convolution Layer
Add another Conv→BN→ReLU→Pool block with 128 channels. Remember to recalculate the flattened size for the FC layer.

#### 7. Use RGB Instead of Grayscale
Remove `transforms.Grayscale()`, change `in_channels=1` to `in_channels=3`, and use ImageNet normalization:
```
Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
```
Color carries useful information (orange tabby vs black lab).

#### 8. Learning Rate Scheduler
```python
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)
```
Decays the learning rate every 5 epochs — helps fine-tune in later stages.

---

### Level 3: Advanced (Stand Out from Everyone)

#### 9. Data Augmentation (Train Only)
```python
train_transforms = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
```
Artificially increases dataset diversity. The test set should NOT be augmented.

#### 10. Grad-CAM Visualization
Show a heatmap of WHERE the model looks to make its decision. If it focuses on the face → good. If it focuses on the background → the model is cheating.

#### 11. Compare Multiple Models
Train a 2-layer CNN vs your 3-layer CNN vs a 4-layer CNN. Plot their accuracies side by side. This demonstrates scientific methodology.

#### 12. Early Stopping
Monitor validation loss each epoch. If it stops improving for 3 epochs, stop training. This prevents overfitting and shows maturity in ML practice.

#### 13. Transfer Learning (Most Impressive)
```python
from torchvision import models
model = models.resnet18(pretrained=True)
model.fc = nn.Linear(512, 2)  # Replace last layer for 2 classes
```
Use a pre-trained model and fine-tune it. Will easily get >95% accuracy and shows you understand modern ML practice.

---

### Recommended Combo for Maximum Impact

Pick **one from each level** to show breadth:
1. Training curves + confusion matrix (shows analysis skills)
2. Add dropout (shows you understand regularization)
3. Test on your own images + Grad-CAM (shows real-world thinking)

This combination tells evaluators: "I didn't just run the code — I understand it, analyzed it, and extended it."

## The Secret: `nn.Linear` + Loss Function = Algorithm

The **same layer** becomes a **different algorithm** depending on which loss function you train it with.

---

### Classification Algorithms

| Layer(s) | Activation | Loss Function | = Algorithm |
| --- | --- | --- | --- |
| `nn.Linear(n, 1)` | Sigmoid | `nn.BCELoss()` | **Logistic Regression** |
| `nn.Linear(n, 2)` | LogSoftmax | `nn.NLLLoss()` | **Softmax Classifier** (your current model) |
| `nn.Linear(n, 2)` | None | `nn.CrossEntropyLoss()` | **Softmax Classifier** (same as above, combined) |
| `nn.Linear(n, 2)` | None | `nn.MultiMarginLoss()` | **SVM (Support Vector Machine)** |
| `nn.Linear(n, k)` → `nn.Linear(k, 2)` | ReLU between | `nn.NLLLoss()` | **MLP (Multi-Layer Perceptron)** |
| `nn.Linear(n, k)` → `nn.Linear(k, 2)` | ReLU between | `nn.MultiMarginLoss()` | **MLP + SVM hybrid** |

---

### Regression Algorithms

| Layer(s) | Activation | Loss Function | = Algorithm |
| --- | --- | --- | --- |
| `nn.Linear(n, 1)` | None | `nn.MSELoss()` | **Linear Regression** |
| `nn.Linear(n, 1)` | None | `nn.L1Loss()` | **Lasso-style Regression** |
| `nn.Linear(n, k)` → `nn.Linear(k, 1)` | ReLU between | `nn.MSELoss()` | **Non-linear Regression (MLP)** |

---

### Your Model Decoded

```
CNN Layers (feature extraction)
        ↓
nn.Linear(1024, 128) + ReLU    ← Hidden layer (makes it MLP, not single perceptron)
        ↓
nn.Linear(128, 2) + LogSoftmax  ← Output layer
        ↓
nn.NLLLoss()                    ← Loss function
        ↓
= CNN + MLP (Softmax Classifier)
```

If you **only** change `nn.NLLLoss()` → `nn.MultiMarginLoss()` and remove `LogSoftmax`:
```
Same CNN + Same Linear layers + Hinge Loss = CNN + SVM
```

---

### Key Insight

> **The layer defines the STRUCTURE (how data flows).**
> **The loss function defines the BEHAVIOR (what the model optimizes for).**
>
> Same structure + different loss = different algorithm.
> Same loss + different structure = different capacity.

---

### Why This Matters

In traditional ML, algorithms are monolithic (you pick SVM or Logistic Regression as a whole package). In deep learning with PyTorch, **you assemble algorithms from parts**:

1. Pick your **layers** (structure) → `nn.Linear`, `nn.Conv2d`
2. Pick your **activation** (non-linearity) → ReLU, Sigmoid, None
3. Pick your **loss** (objective) → NLLLoss, MSELoss, MultiMarginLoss
4. Pick your **optimizer** (how to learn) → Adam, SGD

Different combinations = different algorithms. You're not just using tools — you're building algorithms from first principles.
"""