# -*- coding: utf-8 -*-
"""Copy of U1_MH2_Titanic_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lki_zsSwMkdXzcUL5vrB7zuCqBM81nLD

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objectives

At the end of the mini-hackathon you will be able to:
* Perform Data preprocessing
* Apply different ML algorithms on the **Titanic** dataset
* Perform VotingClassifier

## Dataset Description

The sinking of the Titanic is one of the most infamous shipwrecks in history.

On April 15, 1912, during her maiden voyage, the widely considered “unsinkable” RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone onboard, resulting in the death of many passengers and crew.

While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.

[ Data Set Link: Kaggle competition](https://www.kaggle.com/competitions/titanic)

<br/>

### Data Set Characteristics:

**PassengerId:** Id of the Passenger

**Survived:** Survived or Not information

**Pclass:** Socio-economic status (SES)
  * 1st = Upper
  * 2nd = Middle
  * 3rd = Lower

**Name:** Surname, First Names of the Passenger

**Sex:** Gender of the Passenger

**Age:** Age of the Passenger

**SibSp:**	No. of siblings/spouse of the passenger aboard the Titanic

**Parch:**	No. of parents/children of the passenger aboard the Titanic

**Ticket:**	Ticket number

**Fare:** Passenger fare

**Cabin:**	Cabin number

**Embarked:** Port of Embarkation
  * S = Southampton
  * C = Cherbourg
  * Q = Queenstown

## Problem Statement

Build a predictive model that answers the question: “what sort of people were more likely to survive?” using titanic's passenger data (ie name, age, gender, socio-economic class, etc).
"""

# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/titanic.csv")
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/test_titanic.csv")
    print("Data downloaded successfully")
    return

setup()

!ls

"""## Exercise 1 - Load and Explore the Data (2 Marks)

* Understand different features in the training dataset
* Understand the data types of each column
* Notice the columns of missing values

#### Import Required Packages
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, LogisticRegression,Perceptron, SGDClassifier,RidgeClassifier,PassiveAggressiveClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier,BaggingClassifier

from sklearn.metrics import accuracy_score,classification_report

# Load the dataset
df=pd.read_csv("titanic.csv")



# Getting information about the dataset
df.info()

df.columns

df.dtypes

"""## Exercise 02: Split the data into train and test sets (1 Mark)
Note: Apply all your data preprocessing steps in the train set first and keep the test set aside.
"""

X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

df_train=pd.DataFrame(X_train)

"""## Exercise 03: Data Cleaning and Processing (15 Marks)
### 3.1 Working on the "Cabin" column (2 Marks)
Find unique entries in the Cabin column. We can label all passengers in two categories having a cabin or not. Check the data type(use: type) of each entry of the Cabin. Convert a string data type into '1' i.e. passengers with cabin and others into '0' i.e. passengers without cabin.  Write a function for the above operation and apply it to the cabin column and create another column with the name " Has_cabin" containing only 0 or 1 entries.




"""

df_train['Has_cabin'] = df_train['Cabin'].notna().astype(int)

#Method 2
# def has_cabin(cabin):
#     if type(cabin) == str:
#         return 1
#     else:
#         return 0
#  df['Has_cabin'] = df['Cabin'].apply(has_cabin)

#Method 3
# df['Has_cabin'] = df['Cabin'].apply(lambda x: 1 if type(x) == str else 0)

""" ### 3.2 Working on "SibSp" & "Parch" columns (1 Mark)
Combine columns "SibSp" & "Parch" and create another column that represents the total passengers in one ticket with the name "family_size". In each ticket, there might be Siblings/Spouses (SibSp =Number of Siblings/Spouses Aboard) or Parents/Children (Parch=Number of Parents/Children Aboard ) along with the passenger who booked the ticket.

  
"""

df_train['family_size'] = df_train['SibSp'] + df_train['Parch']+1

#df_train['is_alone']=df_train['family_size'].apply(lambda x:1 else 0).astype(int)



"""### 3.3 Working on the"Embarked" column (2 Marks)
The "embarked" column represents the port of Embarkation: Cherbourg(C), Queenstown(Q), and  Southampton(S ). Thus, the entries are of three categories in this column. Fill in the missing rows in this column. We can fill it with the most frequent category. Map these categorical string entries into numerical.


"""

# impute=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
# df1[['Embarked']]=impute.fit_transform(df1[['Embarked']])

# print(df1[df1['Embarked']==0].shape[0])

df_train['Embarked']=df_train['Embarked'].map({'S':1,'C':2,'Q':3}).fillna(1).astype(int)

df_train['Embarked'].value_counts()

df_train.dtypes

"""### 3.4 Working on the "Age" column (2 Marks)
find the number of NaN entries in the age column and their row index. Calculate the mean, Standard deviation of the Age column and check the distribution of the age column.We can fill the missing values with randomly generated integer values between (mean+Standard deviation, mean-Standard deviation). Use : np.isnan; np.random.randint; concept of slicing dataframe. Convert the age column as an integer data type.


"""

# wrongindex_anull=df['Age'].isna().index
def impute_age(df1):
  np.random.seed(42) #ensure same random Age Values every run
  index_anull=df1[df1['Age'].isna()].index
  ms_sum=np.mean(df1['Age'])+np.std(df1['Age'])
  ms_sub=np.mean(df1['Age'])-np.std(df1['Age'])
  for i in index_anull:
    df1.loc[i,'Age']=np.random.randint(ms_sub,ms_sum)
  df1['Age']=df1['Age'].astype(int)
  return df1
df_train=impute_age(df_train)
df_train['Age'].isna().sum()

"""### 3.5 Working on "sex" column (1 Mark)
Map the Sex column as 'female' : 0, 'male': 1, and convert it into an integer data type.


"""

df_train['Sex'].isna().sum()

df_train['Sex']=df_train['Sex'].map({'male':1,'female':0}).astype(int)

df_train.info()

"""### 3.6  Optional- Working on the "Name" column :
Fetch titles from the name. We can map these titles with numbers and convert them into an integer. Use: concept of the regular expression.

### 3.7 Optional- Working on the "Fare" column :
We can convert face into categorical entries like Low, Medium, and High.


"""

import regex as re
def get_title(name):
    search = re.search(' ([A-Za-z]+)\.', name)

    if search:
        return search.group(1)

    return ""

df1['Title'] = df1['Name'].apply(get_title)

df1['Title'].unique()

df1.info()

df1['Title_Code'] = pd.factorize(df1['Title'])[0] + 1
#second way Label encoding
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['Title_Code'] = le.fit_transform(df['Title'])

df1['Title_Code']

df1['Fare'].isna().sum()

fare_group, bins = pd.cut(
    df1['Fare'],
    bins=3,
    labels=['Low', 'Medium', 'High'],
    retbins=True
)

print(bins)

#Method 2
df1['Fare_Group'] = pd.qcut(
    df['Fare'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

#df1['Fare_Group']
df1['Fare_Group'].value_counts()

df1.groupby('Fare_Group')['Survived'].mean()

df1['Fare_Group']=df1['Fare_Group'].map({'Low':0,'Medium':1,'High':2}).astype(int)

"""### 3.8 Drop the columns (1 Mark)

Drop the columns: - "PassengerId", "Name",  "SibSp" & "Parch", "Tickets", "Cabin"


"""

df_train.drop(columns=['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'],inplace=True)

df_train.columns

df_train.info()

df_train.describe()

fig,axes=plt.subplots(3,3,figsize=(24,27))
axes=axes.flatten()
for i,col in enumerate(df_train.columns):
  df_train.boxplot(column=col,ax=axes[i])
  axes[i].set_title(col,fontsize=15)
#Hide unused sublopts
for j in range(len(df_train.columns),len(axes)):
  axes[j].set_visible(False)
plt.tight_layout()
plt.show()

df_train.corr()

"""### 3.9 Apply Standard Scalar (1 Mark)"""

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(df_train)



"""### 3.10 Create a single function for preprocessing the test set (X_test) and apply it. (4 Marks)
#### **Note**: All the pre-processing steps that were applied on the train set before ML Modelling are also applied on the test set before passing through the predict function.
"""

## Create a function
def preprocess(df_test):
  df_test['Has_cabin'] = df_test['Cabin'].notna().astype(int)
  df_test['family_size'] = df_test['SibSp'] + df_test['Parch']+1
  df_test['Embarked']=df_test['Embarked'].map({'S':1,'C':2,'Q':3}).fillna(1).astype(int)
  df_test=impute_age(df_test)
  df_test['Sex']=df_test['Sex'].map({'male':1,'female':0}).astype(int)
  df_test.drop(columns=['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'],inplace=True,errors='ignore')
  return df_test

## Applyting above function
df_test=pd.DataFrame(X_test)
df_test_preprocess=preprocess(df_test)

df_train.dtypes

df_test_preprocess.dtypes

#df_train.isna().sum().sum()
df_test_preprocess.isna().sum().sum()

"""### 3.11 Apply standard Scalar transformation to x_test (1 Mark)"""

X_test_scaled=scaler.transform(df_test_preprocess)
X_test_scaled.shape

"""## Exercise  4. Apply Multiple ML Algo. along with  Ensemble Technique (Voting classifier) and display the accuracy (7 Marks)
#### Expected Accuracy >= 80%  

"""

models={
    'LogisticRegression':LogisticRegression(C=100,max_iter=5000, random_state=42),
    'KNeighborsClassifier':KNeighborsClassifier(n_neighbors=3),
    #'DecisionTreeClassifier':DecisionTreeClassifier(),
    'SVC':SVC(kernel='linear',probability=True,C=0.1),
    'Perceptron':Perceptron(),
    'SGDClassifier':SGDClassifier(loss='log_loss', max_iter=5000, random_state=42),
    'RidgeClassifier':RidgeClassifier(),
    'PassiveAggressiveClassifier':PassiveAggressiveClassifier(),
    'VotingClassifier':VotingClassifier(estimators=[('lr', LogisticRegression()),
                                                    ('knn',KNeighborsClassifier(n_neighbors=3)),
                                                    ('bg',BaggingClassifier(n_estimators=300,random_state=42)),
                                                     ('svc',SVC(kernel='linear',probability=True,C=0.1))], voting='soft'),
    'BaggingClassifier':BaggingClassifier(n_estimators=300, random_state=42)
}



scores = {}
for name,model in models.items():
  model.fit(X_train_scaled,y_train)
  score=model.score(X_test_scaled,y_test)
  scores[name] = score

for name, score in scores.items():
    print(f"{name:15s}: {score:f}{'>80 %' if score>=0.9 else ''}")

"""## Exercise  5. Pre-process the test_set (3 Marks)
Again we have to apply the same preprocess function and standard scaler on this test set before passing through predict function.

#### Understanding the test set:
"""

# Load the dataset
df_test_set = pd.read_csv("test_titanic.csv")

# Getting information about the dataset
df_test_set.info()

df_test_set['Fare'].fillna(df_test_set['Fare'].mean(), inplace=True)

df_test_set_preprocess=preprocess(df_test_set)

#df_test_set_preprocess.isna().sum().sum()
df_test_set_preprocess.info()



"""#### Note: In the initial train set there were no missing entries in the "Fare" column. But, now for the submission test set, there is one missing entry in this column.

#### There will be a minor change in the preprocess function to address the above issue.
"""

X_test_set_scaled = scaler.transform(df_test_set_preprocess)
print("X_test_scaled shape:", X_test_set_scaled.shape)

"""## Exercise  6. Prediction for test data (2 Mark)"""

# Get PassengerId from original test file (dropped during preprocessing)
passenger_ids = pd.read_csv("test_titanic.csv")['PassengerId']

# Use best model from Exercise 4 - Logistic Regression (81.56% accuracy)
best_model = models['VotingClassifier']

# Predict on the scaled test set
y_pred_test = best_model.predict(X_test_set_scaled)
print
# Create submission DataFrame
submission = pd.DataFrame({
    'PassengerId': passenger_ids,
     'Survived': y_pred_test
 })

print(submission.head(10))
# print("\nTotal predictions:", len(submission))
# print("Survived distribution:\n", submission['Survived'].value_counts())

# # Save to CSV
# submission.to_csv('titanic_submission.csv', index=False)
# print("\nSaved to titanic_submission.csv")

print(df[df['PassengerId']==896])

#Step 1 — Define all features
from itertools import combinations
#combinations — the key idea
all_features = ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Has_cabin', 'familt_size']
best_score = 0
best_features = all_features

# Try dropping 1 or 2 features at a time
for r in [1, 2]:
    for drop_cols in combinations(all_features, r):
        keep_cols = [c for c in all_features if c not in drop_cols] # remaining columns
        idx = [all_features.index(c) for c in keep_cols]  # their column positions (numbers)
        X_sub_train = X_train_scaled[:, idx] #select only those columns
        X_sub_test  = X_test_scaled[:, idx]
        lgs_sub = LogisticRegression(C=10)
        lgs_sub.fit(X_sub_train, y_train)
        score = lgs_sub.score(X_sub_test, y_test)
        if score > best_score:
            best_score = score
            best_features = keep_cols
            best_drop = drop_cols

print(f"Best accuracy : {best_score:.4f}")
print(f"Drop columns  : {best_drop}")
print(f"Keep columns  : {best_features}")