# -*- coding: utf-8 -*-
"""Copy of U1_MH1_Data_Munging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120vH5PWUBivwEFqrYW2kxjffEKtRM7H6

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing
"""

#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

"""## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20
"""

# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

!ls

"""## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv
"""

# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

# YOUR CODE HERE for loading and exploring the datasets
df_basic=pd.read_csv('/content/Districtwise_Basicdata.csv',skiprows=[0])
df_enrollment=pd.read_csv('/content/Districtwise_Enrollment_details_indicator.csv', skiprows=[0,1,2])
#df3=pd.read_csv('/content/Districtwise_Teacher_indicator.csv')

#Option 2
list_basic=df_basic.iloc[0:1,:].to_numpy()[0]
df_basic.columns=list_basic
df_basic=df_basic.drop([0]).reset_index(drop=True)
df_basic.head(3)

#Option 2
list_names=[i.replace(' ','') for i in df_enrollment.iloc[2:3,:].to_numpy()[0]]
df_enrollment.columns=list_names
df_enrollment=df_enrollment.drop([0,1,3]).reset_index(drop=True)
df_enrollment.head(3)

# df_basic.info()
# df_enrollment.info()
# df_basic.columns
df_enrollment.columns

df_enrollment.columns=[s.replace(' ','') for s in df_enrollment.columns]

df_enrollment.columns
#df_enrollment.display(verbose=true)

#metod to find numeric
non_numeric=[]
for i in df_basic.columns:
  if df_basic[i].dtype=='object':
    non_numeric.append(i)
print(non_numeric)

display(df_basic[non_numeric])

non_numeric1=[]
for i in df_enrollment.columns:
  if df_enrollment[i].dtype!='object':
    non_numeric1.append(i)
print(non_numeric1)

display(df_enrollment[non_numeric1].isna().sum().sum())

df_enrollment['T_E_Gov_Schools']=df_enrollment['EnrGovt1']+df_enrollment['EnrGovt2']+df_enrollment['EnrGovt3']+df_enrollment['EnrGovt4']+df_enrollment['EnrGovt5']+df_enrollment['EnrGovt6']+df_enrollment['EnrGovt7']

df_enrollment['T_E_Priv_Schools']=df_enrollment['EnrPvt1']+df_enrollment['EnrPvt2']+df_enrollment['EnrPvt3']+df_enrollment['EnrPvt4']+df_enrollment['EnrPvt5']+df_enrollment['EnrPvt6']+df_enrollment['EnrPvt7']

df_enrollment['T_E_Rur_Govt_Schools']=df_enrollment['EnrRGovt1']+df_enrollment['EnrRGovt2']+df_enrollment['EnrRGovt3']+df_enrollment['EnrRGovt4']+df_enrollment['EnrRGovt5']+df_enrollment['EnrRGovt6']+df_enrollment['EnrRGovt7']

df_enrollment['T_E_Rur_Priv_Schools']=df_enrollment['EnrRPvt1']+df_enrollment['EnrRPvt2']+df_enrollment['EnrRPvt3']+df_enrollment['EnrRPvt4']+df_enrollment['EnrRPvt5']+df_enrollment['EnrRPvt6']+df_enrollment['EnrRPvt7']

df_enrollment['T_E_Py4']=df_enrollment['EnrPy4C1']+df_enrollment['EnrPy4C2']+df_enrollment['EnrPy4C3']+df_enrollment['EnrPy4C4']+df_enrollment['EnrPy4C5']+df_enrollment['EnrPy4C6']+df_enrollment['EnrPy4C7']+df_enrollment['EnrPy4C8']

df_enrollment['T_E_Py3']=df_enrollment['EnrPy3C1']+df_enrollment['EnrPy3C2']+df_enrollment['EnrPy3C3']+df_enrollment['EnrPy3C4']+df_enrollment['EnrPy3C5']+df_enrollment['EnrPy3C6']+df_enrollment['EnrPy3C7']+df_enrollment['EnrPy3C8']

df_enrollment['T_E_Py2']=df_enrollment['EnrPy2C1']+df_enrollment['EnrPy2C2']+df_enrollment['EnrPy2C3']+df_enrollment['EnrPy2C4']+df_enrollment['EnrPy2C5']+df_enrollment['EnrPy2C6']+df_enrollment['EnrPy2C7']+df_enrollment['EnrPy2C8']

df_enrollment['T_E_Py1']=df_enrollment['EnrPy1C1']+df_enrollment['EnrPy1C2']+df_enrollment['EnrPy1C3']+df_enrollment['EnrPy1C4']+df_enrollment['EnrPy1C5']+df_enrollment['EnrPy1C6']+df_enrollment['EnrPy1C7']+df_enrollment['EnrPy1C8']

df_enrollment['T_E_Cy']=df_enrollment['EnrCyC1']+df_enrollment['EnrCyC2']+df_enrollment['EnrCyC3']+df_enrollment['EnrCyC4']+df_enrollment['EnrCyC5']+df_enrollment['EnrCyC6']+df_enrollment['EnrCyC7']+df_enrollment['EnrCyC8']

#SC
df_enrollment['ScGEnrpCy']=df_enrollment['ScgEnrupCy']+df_enrollment['ScgEnrpCy']

df_enrollment['ScBEnrpCy']=df_enrollment['ScEnrupCy']+df_enrollment['ScEnrpCy']-df_enrollment['ScGEnrpCy']

#st
df_enrollment['StGEnrCy']=df_enrollment['StgEnrpCy']+df_enrollment['StgEnrupCy']

df_enrollment['StBEnrCy']=df_enrollment['StEnrpCy']+df_enrollment['StEnrupCy']-df_enrollment['StGEnrCy']

#Ger
# GerpPy2+GerupPy2
# GerpPy1+GerupPy1
# GerpCy+GerupCy

df_enrollment['Gerp_Py2']=df_enrollment['GerpPy2']+df_enrollment['GerupPy2']
df_enrollment['Gerp_Py1']=df_enrollment['GerpPy1']+df_enrollment['GerupPy1']
df_enrollment['Gerp_Cy']=df_enrollment['GerpCy']+df_enrollment['GerupCy']

# NerpPy2+NerupPy2
# NerpPy1+NerupPy1
# NerpCy+NerupCy

df_enrollment['Nerp_Py2']=df_enrollment['NerpPy2']+df_enrollment['NerupPy2']
df_enrollment['Nerp_Py1']=df_enrollment['NerpPy1']+df_enrollment['NerupPy1']
df_enrollment['Nerp_Cy']=df_enrollment['NerpCy']+df_enrollment['NerupCy']

#EnrDisBC1,EnrDisBC2
df_enrollment['T_EnrDisBC']=df_enrollment['EnrDisBC1']+df_enrollment['EnrDisBC2']+df_enrollment['EnrDisBC3']+df_enrollment['EnrDisBC4']+df_enrollment['EnrDisBC5']+df_enrollment['EnrDisBC6']+df_enrollment['EnrDisBC7']+df_enrollment['EnrDisBC8']

#EnrDisGC1
df_enrollment['T_EnrDisGC']=df_enrollment['EnrDisGC1']+df_enrollment['EnrDisGC2']+df_enrollment['EnrDisGC3']+df_enrollment['EnrDisGC4']+df_enrollment['EnrDisGC5']+df_enrollment['EnrDisGC6']+df_enrollment['EnrDisGC7']+df_enrollment['EnrDisGC8']

#TotalGross
#GrossnessP,GrossnessUp

df_enrollment['TotalGross']=df_enrollment['GrossnessP']+df_enrollment['GrossnessUp']

#EnrMed1
#EnrMed11

df_enrollment['T_EnrMed1']=df_enrollment['EnrMed11']+df_enrollment['EnrMed12']+df_enrollment['EnrMed13']+df_enrollment['EnrMed14']+df_enrollment['EnrMed15']+df_enrollment['EnrMed16']+df_enrollment['EnrMed17']

#EnrMed2
#EnrMed21

df_enrollment['T_EnrMed2']=df_enrollment['EnrMed21']+df_enrollment['EnrMed22']+df_enrollment['EnrMed23']+df_enrollment['EnrMed24']+df_enrollment['EnrMed25']+df_enrollment['EnrMed26']+df_enrollment['EnrMed27']

#EnrMed3
#EnrMed31

df_enrollment['T_EnrMed3']=df_enrollment['EnrMed31']+df_enrollment['EnrMed32']+df_enrollment['EnrMed33']+df_enrollment['EnrMed34']+df_enrollment['EnrMed35']+df_enrollment['EnrMed36']+df_enrollment['EnrMed37']



#RepC1
#RepC8
#Repeaters
df_enrollment['T_R']=df_enrollment['RepC1']+df_enrollment['RepC2']+df_enrollment['RepC3']+df_enrollment['RepC4']+df_enrollment['RepC5']+df_enrollment['RepC6']+df_enrollment['RepC7']+df_enrollment['RepC8']



#MuslimG
#MuslimGP+MuslimGUp
df_enrollment['T_Muslim_G']=df_enrollment['MuslimGP']+df_enrollment['MuslimGUp']


#

#MusilB=MuslimUp+MuslimP- MuslimGUp

df_enrollment['T_Muslim_B']=df_enrollment['MuslimP']+df_enrollment['MuslimUp']- df_enrollment['T_Muslim_G']


#OBCG=ObcGUp+ObcGP
#OBCB=ObcP+ObcUp
df_enrollment['T_OBC_G']=df_enrollment['ObcGUp']+df_enrollment['ObcGP']

df_enrollment['T_OBC_B']=df_enrollment['ObcP']+df_enrollment['ObcUp']- df_enrollment['T_OBC_G']

# #Option 2
# # Clean column names by removing spaces
# df_enrollment.columns=[s.replace(' ','') for s in df_enrollment.columns]
# # Drop the first row (original row 3), as it might be a duplicate header or metadata
# df_enrollment=df_enrollment.drop([0]).reset_index(drop=True)

# # Convert Statecd and distcd to numeric, coercing errors to handle any non-numeric values
# df_enrollment['Statecd'] = pd.to_numeric(df_enrollment['Statecd'], errors='coerce')
# df_enrollment['distcd'] = pd.to_numeric(df_enrollment['distcd'], errors='coerce')

# df_enrollment.head(3)
# df_enrollment.info()

(df_enrollment.columns.tolist())

cols_to_drop = [
    'EnrGovt1','EnrGovt2','EnrGovt3','EnrGovt4','EnrGovt5','EnrGovt6','EnrGovt7','EnrGovt9','EnrPvt1',
    'EnrPvt2','EnrPvt3','EnrPvt4','EnrPvt5','EnrPvt6','EnrPvt7','EnrPvt9','EnrRGovt1','EnrRGovt2',
    'EnrRGovt3','EnrRGovt4','EnrRGovt5','EnrRGovt6','EnrRGovt7','EnrRGovt9','EnrRPvt1','EnrRPvt2',
    'EnrRPvt3','EnrRPvt4','EnrRPvt5','EnrRPvt6','EnrRPvt7','EnrRPvt9','EnrPy4C1','EnrPy4C2','EnrPy4C3',
    'EnrPy4C4','EnrPy4C5','EnrPy4C6','EnrPy4C7','EnrPy4C8','EnrPy3C1','EnrPy3C2','EnrPy3C3','EnrPy3C4',
    'EnrPy3C5','EnrPy3C6','EnrPy3C7','EnrPy3C8','EnrPy2C1','EnrPy2C2','EnrPy2C3','EnrPy2C4','EnrPy2C5',
    'EnrPy2C6','EnrPy2C7','EnrPy2C8','EnrPy1C1','EnrPy1C2','EnrPy1C3','EnrPy1C4','EnrPy1C5','EnrPy1C6',
    'EnrPy1C7','EnrPy1C8','EnrCyC1','EnrCyC2','EnrCyC3','EnrCyC4','EnrCyC5','EnrCyC6','EnrCyC7','EnrCyC8',
    'ScEnrpCy','ScEnrupCy','ScgEnrpCy','ScgEnrupCy','StEnrpCy','StgEnrpCy','StEnrupCy','StgEnrupCy',
    'GerpPy2','GerpPy1','GerpCy','GerupPy2','GerupPy1','GerupCy','NerpPy2','NerpPy1','NerpCy','NerupPy2',
    'NerupPy1','NerupCy','EnrGC1','EnrGC2','EnrGC3','EnrGC4','EnrGC5','EnrGC6','EnrGC7','EnrGC8',
    'EnrDisBC1','EnrDisBC2','EnrDisBC3','EnrDisBC4','EnrDisBC5','EnrDisBC6','EnrDisBC7','EnrDisBC8',
    'EnrDisGC1','EnrDisGC2','EnrDisGC3','EnrDisGC4','EnrDisGC5','EnrDisGC6','EnrDisGC7','EnrDisGC8',
    'GrossnessP','GrossnessUp','EnrMed11','EnrMed12','EnrMed13','EnrMed14','EnrMed15','EnrMed16','EnrMed17',
    'EnrMed21','EnrMed22','EnrMed23','EnrMed24','EnrMed25','EnrMed26','EnrMed27','EnrMed31','EnrMed32',
    'EnrMed33','EnrMed34','EnrMed35','EnrMed36','EnrMed37','RepC1','RepC2','RepC3','RepC4','RepC5','RepC6',
    'RepC7','RepC8','MuslimP','MuslimUp','MuslimGP','MuslimGUp','ObcP','ObcUp','ObcGP','ObcGUp','ScGEnrpCy',
    'ScBEnrpCy','StGEnrCy','StBEnrCy','Gerp_Py2','Gerp_Py1','Gerp_Cy','Nerp_Py2','Nerp_Py1','Nerp_Cy'
]
df_enrollment = df_enrollment.drop(cols_to_drop, axis=1)

#df_enrollment.head(1).display(verbose=True)

display(df_enrollment.isnull().sum().sum())

"""## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

"""

# YOUR CODE HERE for integrating the datasets
#create unique identifier columns in both data frames
df_basic['uid']= df_basic['Year'].astype(str)+'_'+df_basic['Statecd'].astype(str)+'_'+df_basic['distcd'].astype(str)
df_enrollment['uid']= df_enrollment['Year'].astype(str)+'_'+df_enrollment['Statecd'].astype(str)+'_'+df_enrollment['distcd'].astype(str)

#set the identifier as index

df_basic.set_index('uid',inplace=True)
df_enrollment.set_index('uid',inplace=True)

#integrate the dataframes using index

df_merged= df_basic.join(df_enrollment,lsuffix='_basic',rsuffix='_enroll')

#Display the merged data frame

display(df_merged.head(3))

df_merged.iloc[:,17:30]

df_merged.drop(['statename','distname_basic','Year_enroll','Statecd_enroll','StateName','distcd_enroll','distname_enroll']
               ,axis=1,inplace=True)

df_merged.shape

"""## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values



"""

# YOUR CODE HERE for data cleaning
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df_merged['overall_lit']=le.fit_transform(df_merged['overall_lit'])
le1=LabelEncoder()
df_merged['Year_basic']=le1.fit_transform(df_merged['Year_basic'])

#

df_merged['overall_lit'].value_counts()

df_merged.dtypes

nan_counts=df_merged.isna().sum().sort_values(ascending=False)
print(f"Total Nan Values : {nan_counts.sum()}")
print(f"Columns with Nan : {(nan_counts>0).sum()} out of {len(nan_counts)}")
print("\n Top 20 columns with most Nan values")
print(nan_counts[nan_counts > 0].head(178))
print(nan_counts)

"""## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.
"""

df_merged.dtypes

# df_merged['p_sc_pop'].dropna()

# # YOUR CODE HERE for cleaning the dataframe
# import pandas as pd

# # Identify columns that are currently 'object' type and should be numeric
# object_cols_to_convert = []
# for col in df_merged.columns:
#     if df_merged[col].dtype == 'object':
#         object_cols_to_convert.append(col)

# # Convert identified object columns to numeric, coercing errors to NaN
# # This ensures that all columns intended to be numeric are correctly typed.
# for col in object_cols_to_convert:
#     df_merged[col] = pd.to_numeric(df_merged[col], errors='coerce')

# # Now, fill NaN values with the median of only the numeric columns.
# # The 'numeric_only=True' argument ensures that median is calculated only for numeric columns.
# df_merged.fillna(df_merged.median(numeric_only=True), inplace=True)

df_merged.fillna(df_merged.median(), inplace=True)
print("Nan values" ,df_merged.isna().sum().sum())
print("duplicated",df_merged.duplicated().sum())

df_merged.isna().sum().sum()

"""### Using `SimpleImputer` for Missing Value Imputation

`SimpleImputer` is a scikit-learn preprocessing class used to fill missing values in datasets. It can impute values using various strategies like:

*   **'mean'**: Replaces missing values with the mean of the column.
*   **'median'**: Replaces missing values with the median of the column.
*   **'most_frequent'**: Replaces missing values with the most frequent value (mode) of the column.
*   **'constant'**: Replaces missing values with a specified constant value.

It's often preferred in machine learning workflows because it allows you to `fit` the imputer on your training data and then `transform` both training and test data, preventing data leakage.
"""

# from sklearn.impute import SimpleImputer
# import numpy as np
# import pandas as pd

# # Let's create a sample DataFrame to demonstrate SimpleImputer
# dummy_data = {
#     'col1': [1, 2, np.nan, 4, 5],
#     'col2': [10, np.nan, 30, 40, 50],
#     'col3': ['A', 'B', 'A', np.nan, 'C']
# }
# df_sample = pd.DataFrame(dummy_data)
# print("Original DataFrame with NaNs:")
# display(df_sample)

# # Impute numerical columns with the median strategy
# # Select only numeric columns for median imputation
# numeric_cols = df_sample.select_dtypes(include=np.number).columns
# imputer_numeric = SimpleImputer(strategy='median')
# df_sample[numeric_cols] = imputer_numeric.fit_transform(df_sample[numeric_cols])

# # Impute categorical columns with the most_frequent strategy
# categorical_cols = df_sample.select_dtypes(include='object').columns
# imputer_categorical = SimpleImputer(strategy='most_frequent')
# df_sample[categorical_cols] = imputer_categorical.fit_transform(df_sample[categorical_cols])

# print("\nDataFrame after imputation with SimpleImputer:")
# display(df_sample)

df_merged.shape

"""## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.
"""

def remove_Highly_Correlated(df, bar=0.9):
  # Creates correlation matrix
  corr = df.corr()

  # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

# YOUR CODE HERE to remove highly correlated features from the dataframe by calling above function.
reduced_df=remove_Highly_Correlated(df_merged)

"""## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)
"""

# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler


#seperate the target variable
y=reduced_df['overall_lit']
X=reduced_df.drop('overall_lit',axis=1)
#Apply scaler
scaler=StandardScaler()
X_scaled=pd.DataFrame(scaler.fit_transform(X),columns=X.columns,index=X.index)
print(X_scaled.shape)
print(y.shape)

"""## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%
"""

from sklearn.linear_model import LinearRegression,LogisticRegression,Perceptron,SGDClassifier,RidgeClassifier,PassiveAggressiveClassifier,LogisticRegressionCV

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression, Perceptron, SGDClassifier, RidgeClassifier, PassiveAggressiveClassifier, LogisticRegressionCV
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier,VotingClassifier

# YOUR CODE HERE for applying different classifiers
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape,y_train.shape,y_test.shape

import numpy as np
from sklearn.linear_model import LinearRegression,LogisticRegression,Perceptron,SGDClassifier,RidgeClassifier,PassiveAggressiveClassifier,LogisticRegressionCV
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier,VotingClassifier

model_dict={
        'LR':LogisticRegression(C=100,max_iter=50000, random_state=42),
       'per':Perceptron(random_state=42),
       'sgd':SGDClassifier(loss='log_loss', max_iter=50000, random_state=42), # Changed to log_loss for soft voting
       'rc':RidgeClassifier(random_state=42),
       'PA':PassiveAggressiveClassifier(random_state=42),
       'LRC':LogisticRegressionCV(max_iter=100000, random_state=42),
       'knn':KNeighborsClassifier(),
       'sv':SVC(kernel='linear', probability=True, random_state=42),
       'Bagg':BaggingClassifier(n_estimators=300, random_state=42), # Updated n_estimators to 300
}

# Define the estimators for the VotingClassifier with 'soft' voting
# Select high-performing models that support predict_proba
estimators_for_voting = [
    ('LR', LogisticRegression(C=100, max_iter=50000, random_state=42)),
    #('LRC', LogisticRegressionCV(max_iter=50000, random_state=42)),
    ('sv', SVC(kernel='rbf',C=100, probability=True, random_state=42)),
    ('Bagg', BaggingClassifier(n_estimators=100, random_state=42)),
    #('sgd', SGDClassifier(loss='log_loss', max_iter=50000, random_state=42)) # Use sgd with log_loss
]

# Assign weights, giving higher weight to the best performing model (Bagg)
#weights_for_voting = [1, 1, 1, 3, 1] # LR, LRC, SVC, Bagg (weight 3), SGD

model_dict['voting'] = VotingClassifier(estimators=estimators_for_voting, voting='hard')

scores = {}
for name,model in model_dict.items():
  model.fit(X_train,y_train)
  score=model.score(X_test,y_test)
  scores[name] = score

for name, score in scores.items():
    print(f"{name:15s}: {score:f}{'>90 %' if score>=0.9 else ''}")